# base
seed: 0
deterministic: True

# environment config
device: cpu     # examples: [0], [0,1], [1,2,3], cpu... 

# project config
project: model/AE
name: MNIST

# model config
model_type: AE          # [AE, CAE]
denoising: False        # if True, denoising autoencder will be trained
noise_mean: 0
noise_std: 0.1

# image setting config
height: 28
width: 28
color_channel: 1
convert2grayscale: False

# data config
MNIST_train: True       # if True, MNIST will be loaded automatically
MNIST:
    path: data/
    MNIST_valset_proportion: 0.2      # MNIST has only train and test data. Thus, part of the training data is used as a validation set.
CUSTOM:
    custom_data_proportion: [0.7, 0.3]
    two_folders": ["val", "test"]
    train_data_path: null
    val_data_path: null
    test_data_path: null


# base_path: ./
# model_name: AE_MNIST_10epochs
# data_name: data1
# loss_data_name: AE_MNIST_10epochs





batch_size: 128
epochs: 10,
lr": 0.001,
hidden_dim: 256
latent_dim: 32
dropout: 0.1

result_num: 10
result_img_name: result_AE_10epcohs.png
visualization: 1
visualization_img_name: visualization_AE_10epochs.png